#############                                                                              
### INPUT ###                                                                              
#############                                                                              
                                                                                           
# https://wiki.hypr.land/Configuring/Variables/#input                                      
input {                                                                                    
    kb_layout = us, in                                                                     
    kb_variant = ,eng                                                                      
    kb_model =                                                                             
    kb_options =                                                                           
    kb_rules =                                                                             
                                                                                           
    follow_mouse = 1                                                                       
                                                                                           
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.                                 
                                                                                           
    touchpad {
        # Use natural (inverse) scrolling
        # natural_scroll = true

        # Use two-finger clicks for right-click instead of lower-right corner
        # clickfinger_behavior = true

        # Control the speed of your scrolling
        scroll_factor = 0.4

        # Enable the touchpad while typing
        # disable_while_typing = false

        # Left-click-and-drag with three fingers
        # drag_3fg = 1                                                        
    }                                                                                      
}                                                                                          

# See https://wiki.hypr.land/Configuring/Gestures                                          
gesture = 3, horizontal, workspace                                                         
                                                                                           
# Example per-device config                                                                
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more       
device {                                                                                   
    name = epic-mouse-v1                                                                   
    sensitivity = -0.5                                                                     
}                                                                                          
                                                                                           
                                                                                           
