##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Suppress maximize events
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix XWayland drag issues
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run placement
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = true
}

# Floating rules for common apps
windowrule {
    name = floating-utilities
    match:class = ^(pavucontrol|blueman-manager|nm-connection-editor|nm-applet)$
    float = true
}

windowrule {
    name = floating-media
    match:class = ^(imv|mpv|feh)$
    float = true
}

# Explicit rules for feh
windowrulev = float, class:^(feh)$
windowrulev = size 1000 600, class:^(feh)$
windowrulev = center, class:^(feh)$


# File managers
windowrule {
    name = floating-file-managers
    match:class = ^(nautilus|thunar)$
    float = true
    size = 1000 600
}

# File dialogs
windowrule {
    name = floating-file-dialogs
    match:title = ^(Open File|Save File|File Picker|Select a File|Choose Download Folder)$
    float = true
    size = 800 500
}

# Floating terminal (Quick Settings sub-panels)
windowrule {
    name = floating-term
    match:class = ^(floating-term)$
    float = true
    size = 650 450
    center = true
}

# Floating terminal (About PC)
windowrule {
    name = meduim-floating-term
    match:class = ^(meduim-floating-term)
    float = true
    size = 800 600
    center =true
}


# Large floating terminal (Config editing)
windowrule {
    name = large-floating-term
    match:class = ^(large-floating-term)$
    float = true
    size = 1000 750
    center = true
}

# Center all floating windows
windowrule {
    name = center-floating
    match:float = true
    center = true
}
