# Light Theme Configuration
general {
    col.active_border   = rgba(005fbcaa) rgba(0088ccaa) 45deg
    col.inactive_border = rgba(0000001a)
}

decoration {
    shadow {
        color = rgba(00000033)
    }
}

# Blur effects
blurls = wlogout
blurls = rofi
