# Catppuccin Latte (Light)
set -g fish_color_normal 4c4f69
set -g fish_color_command 1e66f5
set -g fish_color_param dd7878
set -g fish_color_keyword d20f39
set -g fish_color_quote 40a02b
set -g fish_color_redirection fe640b
set -g fish_color_end fe640b
set -g fish_color_error d20f39
set -g fish_color_comment 7c7f93
set -g fish_color_selection --background=acb0be
set -g fish_color_search_match --background=acb0be
set -g fish_color_operator 179287
set -g fish_color_escape 179287
set -g fish_color_autosuggestion 9ca0b0
set -g fish_color_cancel d20f39
set -g fish_color_cwd df8e1d
set -g fish_color_user 179287
set -g fish_color_host 1e66f5
set -g fish_color_host_remote 40a02b
set -g fish_color_status d20f39
set -g fish_pager_color_progress 9ca0b0
set -g fish_pager_color_prefix ea76cb
set -g fish_pager_color_completion 4c4f69
set -g fish_pager_color_description 9ca0b0

# Prompt colors
set -g fish_prompt_color_logo 1e66f5
set -g fish_prompt_color_time 8839ef
set -g fish_prompt_color_user 179299
set -g fish_prompt_color_cwd df8e1d
set -g fish_prompt_color_git ea76cb
set -g fish_prompt_color_symbol df8e1d
