[colors.primary]
background = "#eff1f5" # base
foreground = "#4c4f69" # text

[colors.cursor]
text = "#eff1f5"      # base
cursor = "#dc8a78"    # rosewater

[colors.selection]
text = "#eff1f5"      # base
background = "#dc8a78" # rosewater

[colors.normal]
black = "#5c5f77"     # surface1
red = "#d20f39"       # red
green = "#40a02b"     # green
yellow = "#df8e1d"    # yellow
blue = "#1e66f5"      # blue
magenta = "#ea76cb"   # pink
cyan = "#179299"      # teal
white = "#acb0be"     # subtext1

[colors.bright]
black = "#6c6f85"     # surface2
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#bcc0cc"     # subtext0