# Light theme for kitty

foreground            #1a1c20
background            #d3dae3
selection_foreground  #d3dae3
selection_background   #f2b311
cursor                #f2b311
cursor_text_color     #d3dae3
url_color             #f2b311

color0   #d3dae3
color1   #6d45ff
color2   #71f79f
color3   #fdbc4b
color4   #2187fc
color5   #5c626c
color6   #00c1e4
color7   #666a73
color8   #353945
color9   #6d45ff
color10  #71f79f
color11  #fdbc4b
color12  #f2b311
color13  #6d45ff
color14  #00c1e4
color15  #1a1c20

active_border_color   #f2b311
inactive_border_color #d3dae3
bell_border_color     #6d45ff

# Tab bar colors
active_tab_background #6d45ff
active_tab_foreground #1a1c20
inactive_tab_background #d3dae3
inactive_tab_foreground #666a73